In [60]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
GITHUB_TOKEN = "YOUR_GITHUB_TOKEN_HERE"

In [61]:
!git clone https://gyxnova:GITHUB_TOKEN@github.com/gyxnova/deep-past-mt.git

Cloning into 'deep-past-mt'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (6/6), done.
remote: Total 8 (delta 0), reused 5 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (8/8), done.

In [62]:
%cd deep-past-mt

/content/deep-past-mt/deep-past-mt

In [63]:
!pip install -r requirements.txt

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 2)) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 3)) (1.6.1)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 4)) (2.9.0+cpu)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 5)) (5.0.0)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 6)) (0.2.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 7)) (3.10.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 8)) (4.67.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 1)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 1)) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r requirements.txt (line 3)) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r requirements.txt (line 3)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 4)) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 4)) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 4)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 4)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 4)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 4)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 4)) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 5)) (1.3.7)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 5)) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 5)) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 5)) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 5)) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 5)) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 5)) (0.7.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 7)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 7)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 7)) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 7)) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 7)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 7)) (3.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 5)) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 5)) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 5)) (1.5.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 1)) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->-r requirements.txt (line 4)) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->-r requirements.txt (line 4)) (3.0.3)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers->-r requirements.txt (line 5)) (8.3.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 5)) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 5)) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 5)) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 5)) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 5)) (0.16.0)

In [64]:
import zipfile
import os

# Path to the zip in your Drive
zip_path = "/content/drive/MyDrive/deep-past/data/deep-past-initiative-machine-translation.zip"

# Path where we will extract
extract_path = "/content/drive/MyDrive/deep-past/data/extracted"

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extraction completed!")

Extraction completed!

In [65]:
DATA_PATH = "/content/drive/MyDrive/deep-past/data/extracted"
os.listdir(DATA_PATH)

['OA_Lexicon_eBL.csv',
 'Sentences_Oare_FirstWord_LinNum.csv',
 'bibliography.csv',
 'eBL_Dictionary.csv',
 'publications.csv',
 'published_texts.csv',
 'resources.csv',
 'sample_submission.csv',
 'test.csv',
 'train.csv']

In [66]:
import pandas as pd

train_df = pd.read_csv(os.path.join(DATA_PATH, "train.csv"))
test_df  = pd.read_csv(os.path.join(DATA_PATH, "test.csv"))
pub_df   = pd.read_csv(os.path.join(DATA_PATH, "publications.csv"))

print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)
print("Publications shape:", pub_df.shape)

Train shape: (1561, 3)
Test shape: (4, 5)
Publications shape: (216602, 4)

In [67]:
train_df.sample(5)

,oare_id,transliteration,translation
1243,c5a99a9f-96b5-4aa2-8198-b1d7c79d2610,10 GÍN KÙ.BABBAR ṣa-ru-pá-am iš-tù ḫa-mu-uš-ti...,10 shekels of refined silver he will send to m...
285,2d1b0c9a-4403-4255-8198-406e3501a4ab,4 GÚ 42 ma-na URUDU iš-tí i-dí-(d)MAR.TU 0.5 m...,4 talents 42 minas of copper with Iddin-Aurum....
980,9a8ef84b-615a-499e-9b11-ddeba04dba43,um-ma en-nam-a-šùr ù da-dí-a-ma a-na e-lá-ma q...,"Thus Ennam-Aššur and Dadiya, say to Elamma: Of..."
964,988f713f-9400-4559-9953-8a8e8e350ce9,6 GÍN KÙ.BABBAR PUZUR₄-a-šur DUMU a-šur-dan 2....,6 shekels of silver: Puzur-Aššur son of Aššur-...
1487,f396e4b6-939c-4bd1-b192-732513f7d36b,0.66666 ma-na KÙ.BABBAR ṣa-ru-pá-am i-na ma-na...,0.6666 mina of refined silver - he cut it off ...

In [68]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1561 entries, 0 to 1560
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   oare_id          1561 non-null   object
 1   transliteration  1561 non-null   object
 2   translation      1561 non-null   object
dtypes: object(3)
memory usage: 36.7+ KB

In [69]:
train_df['transliteration'].str.len().describe()

count    1561.000000
mean      426.459321
std       269.688193
min        21.000000
25%       204.000000
50%       365.000000
75%       632.000000
max       932.000000
Name: transliteration, dtype: float64

In [70]:
train_df['translation'].str.len().describe()

count    1561.000000
mean      499.723895
std       466.365112
min         6.000000
25%       172.000000
50%       383.000000
75%       681.000000
max      3895.000000
Name: translation, dtype: float64

In [71]:
train_df.duplicated().sum()

np.int64(0)

In [72]:
pub_df.sample(5)

,pdf_name,page,page_text,has_akkadian
41613,CAD (N-Z).pdf,2749,iaknu 4b\nSa GAR ] the assistant of the househ...,False
177769,afo_realien.pdf,2708,"Sprachform) [Bd. 38/39 (1991/1992), S. 327]. B...",False
157557,Schorr_Urkunden_Altbabylonischen_Zivil_und_Pro...,462,406\nAltbabylonische Rechtsurlrunden.\nl5 e-ii...,False
18871,"Blum, H., Faist, B. et al eds - Bruckenland An...",321,"310\nThomas Richter\nbeschrieben werden, ersch...",False
64704,"EL 1, 1930.pdf",285,"264 G. Eißer u. J. Lewy, Die altassyr. Rechtsu...",True

In [73]:
pub_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216602 entries, 0 to 216601
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   pdf_name      216602 non-null  object
 1   page          216602 non-null  int64
 2   page_text     216602 non-null  object
 3   has_akkadian  216602 non-null  bool
dtypes: bool(1), int64(1), object(2)
memory usage: 5.2+ MB

In [74]:
pub_df.duplicated().sum()

np.int64(108737)