In [121]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [122]:
GITHUB_TOKEN = "YOUR_GITHUB_TOKEN_HERE"

In [123]:
!git clone https://gyxnova:GITHUB_TOKEN@github.com/gyxnova/deep-past-mt.git

Cloning into 'deep-past-mt'...
remote: Enumerating objects: 12, done.
remote: Counting objects: 100% (12/12), done.
remote: Compressing objects: 100% (10/10), done.
remote: Total 12 (delta 0), reused 9 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (12/12), 13.53 KiB | 13.53 MiB/s, done.

In [124]:
%cd deep-past-mt

/content/deep-past-mt/deep-past-mt/deep-past-mt/deep-past-mt

In [125]:
!pip install -r requirements.txt

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 1)) (2.2.2)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 2)) (2.0.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 3)) (1.6.1)
Requirement already satisfied: torch in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 4)) (2.9.0+cpu)
Requirement already satisfied: transformers in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 5)) (5.0.0)
Requirement already satisfied: sentencepiece in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 6)) (0.2.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 7)) (3.10.0)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from -r requirements.txt (line 8)) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 1)) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 1)) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas->-r requirements.txt (line 1)) (2025.3)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r requirements.txt (line 3)) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r requirements.txt (line 3)) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn->-r requirements.txt (line 3)) (3.6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 4)) (3.20.3)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 4)) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 4)) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 4)) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 4)) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 4)) (3.1.6)
Requirement already satisfied: fsspec>=0.8.5 in /usr/local/lib/python3.12/dist-packages (from torch->-r requirements.txt (line 4)) (2025.3.0)
Requirement already satisfied: huggingface-hub<2.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 5)) (1.4.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 5)) (26.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 5)) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 5)) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 5)) (0.22.2)
Requirement already satisfied: typer-slim in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 5)) (0.21.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers->-r requirements.txt (line 5)) (0.7.0)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 7)) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 7)) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 7)) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 7)) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 7)) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->-r requirements.txt (line 7)) (3.3.2)
Requirement already satisfied: hf-xet<2.0.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 5)) (1.2.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 5)) (0.28.1)
Requirement already satisfied: shellingham in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 5)) (1.5.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas->-r requirements.txt (line 1)) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch->-r requirements.txt (line 4)) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch->-r requirements.txt (line 4)) (3.0.3)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim->transformers->-r requirements.txt (line 5)) (8.3.1)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 5)) (4.12.1)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 5)) (2026.1.4)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 5)) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 5)) (3.11)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub<2.0,>=1.3.0->transformers->-r requirements.txt (line 5)) (0.16.0)

In [126]:
import zipfile
import os

# Path to the zip in your Drive
zip_path = "/content/drive/MyDrive/deep-past/data/deep-past-initiative-machine-translation.zip"

# Path where we will extract
extract_path = "/content/drive/MyDrive/deep-past/data/extracted"

os.makedirs(extract_path, exist_ok=True)

with zipfile.ZipFile(zip_path, 'r') as zip_ref:
    zip_ref.extractall(extract_path)

print("Extraction completed!")

Extraction completed!

In [127]:
DATA_PATH = "/content/drive/MyDrive/deep-past/data/extracted"
os.listdir(DATA_PATH)

['publications.csv',
 'published_texts.csv',
 'eBL_Dictionary.csv',
 'Sentences_Oare_FirstWord_LinNum.csv',
 'OA_Lexicon_eBL.csv',
 'bibliography.csv',
 'test.csv',
 'resources.csv',
 'sample_submission.csv',
 'train.csv']

In [128]:
import pandas as pd

train_df = pd.read_csv(os.path.join(DATA_PATH, 'train.csv'))
test_df  = pd.read_csv(os.path.join(DATA_PATH, 'test.csv'))
pub_df   = pd.read_csv(os.path.join(DATA_PATH, 'publications.csv'))
lexi_df   = pd.read_csv(os.path.join(DATA_PATH, 'OA_Lexicon_eBL.csv'))
linnum_df   = pd.read_csv(os.path.join(DATA_PATH, 'Sentences_Oare_FirstWord_LinNum.csv'))
bib_df   = pd.read_csv(os.path.join(DATA_PATH, 'bibliography.csv'))
dict_df   = pd.read_csv(os.path.join(DATA_PATH, 'eBL_Dictionary.csv'))
publ_df   = pd.read_csv(os.path.join(DATA_PATH, 'published_texts.csv'))
res_df   = pd.read_csv(os.path.join(DATA_PATH, 'resources.csv'))
ss_df   = pd.read_csv(os.path.join(DATA_PATH, 'sample_submission.csv'))

print("Train shape:", train_df.shape)
print("Test shape:", test_df.shape)
print("Publications shape:", pub_df.shape)
print("Lexicon shape:", lexi_df.shape)
print("linnum shape:", linnum_df.shape)
print("Bibliography shape:", bib_df.shape)
print("Dictionary shape:", dict_df.shape)
print("Published texts shape:", publ_df.shape)
print("Resources shape:", res_df.shape)
print("Sample submission shape:", ss_df.shape)

Train shape: (1561, 3)
Test shape: (4, 5)
Publications shape: (216602, 4)
Lexicon shape: (39332, 9)
linnum shape: (9782, 12)
Bibliography shape: (878, 8)
Dictionary shape: (19215, 3)
Published texts shape: (7953, 19)
Resources shape: (292, 16)
Sample submission shape: (4, 2)

In [129]:
train_df.sample(5)

,oare_id,transliteration,translation
611,5e71c0aa-de0d-4c4f-b87a-aa9a58ea1f39,KIŠIB lu-zi-na KIŠIB a-šur-DU₁₀ ša ḫu-bu-ul a-...,"Seal of Luzina, seal of Aššur-ṭāb, of the debt..."
514,4eb23b20-e6ce-4c45-ac07-07d62a2ef0d0,ma-na KÙ.KI … DUMU sà-aḫ-ru-da-nim … iš-tù ḫa-...,? minas of ... owed by ... son of Sahrudannum....
1134,b579fd6a-35c8-4905-beb9-5606cc240867,KIŠIB ḫi-na-a KIŠIB i-ku-pí-a-šùr DUMU en-um-a...,"Seal of hinnāya, seal of Ikuppi-Aššur, son of ..."
249,277b9f27-719e-42f6-afdd-cdf74fc2310f,a-na ir-ma-a-šur qí-bí-ma um-ma en-um-a-šur-ma...,"Say to Ir'am-Aššur, thus Ennam-Aššur: When in ..."
966,98cd1550-6086-46d3-a89a-e411575afca0,um-me-a-nu šu-lá-ba-an ku-ku-lá-num MAŠKIM ša ...,"Šu-Laban's investors, Kukkulānum, the attorney..."

In [130]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1561 entries, 0 to 1560
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   oare_id          1561 non-null   object
 1   transliteration  1561 non-null   object
 2   translation      1561 non-null   object
dtypes: object(3)
memory usage: 36.7+ KB

In [131]:
train_df['transliteration'].str.len().describe()

count    1561.000000
mean      426.459321
std       269.688193
min        21.000000
25%       204.000000
50%       365.000000
75%       632.000000
max       932.000000
Name: transliteration, dtype: float64

In [132]:
train_df['translation'].str.len().describe()

count    1561.000000
mean      499.723895
std       466.365112
min         6.000000
25%       172.000000
50%       383.000000
75%       681.000000
max      3895.000000
Name: translation, dtype: float64

In [133]:
train_df.duplicated().sum()

np.int64(0)

In [134]:
pub_df.sample(5)

,pdf_name,page,page_text,has_akkadian
190599,"Veenhof, K. & Eidem, J. - Mesopotamia, The Old...",215,"The Old Assyrian Period\nII and lb, and the tw...",False
86095,Kawakami_2006_AlRafidan27_loc_Purushanta.PDF.pdf,10,68\nNaohiko KAWAKAMI\norder to clear up the ma...,False
152094,"Renger, Johannes ed - Assur -- Gott, Stadt und...",47,34\nFriedhelm Pedde\nDIE PALASTGRUNDRISSE VOM ...,False
13666,"Barjamovic, Gojko - A Historical Geography of ...",112,"4.1 HAHHUM\nPurushaddum (7 attestations, 3 'it...",False
11901,"ATHE, 1960.pdf",13,"RECHTSURKUNDEN\nVERPFLICHTUNGSSCHEIN\nHülle, s...",True

In [135]:
pub_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 216602 entries, 0 to 216601
Data columns (total 4 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   pdf_name      216602 non-null  object
 1   page          216602 non-null  int64
 2   page_text     216602 non-null  object
 3   has_akkadian  216602 non-null  bool
dtypes: bool(1), int64(1), object(2)
memory usage: 5.2+ MB

In [136]:
pub_df.duplicated().sum()

np.int64(108737)

In [137]:
pub_df.drop_duplicates(inplace=True)
pub_df.duplicated().sum()

np.int64(0)

In [138]:
pub_df.shape

(107865, 4)

In [139]:
# linnum_df.sample(5)

In [140]:
# linnum_df.info()

In [141]:
# lexi_df.sample(5)

In [142]:
# lexi_df.info()

In [143]:
# bib_df.sample(5)

In [144]:
# bib_df.info()

In [145]:
# dict_df.sample(5)

In [146]:
# dict_df.info()

In [147]:
# res_df.sample(5)

In [148]:
# res_df.info()

In [149]:
# publ_df.sample(5)

In [150]:
# publ_df.info()

In [151]:
import pandas as pd
import re

subscript_map = str.maketrans("₀₁₂₃₄₅₆₇₈₉ₓ", "0123456789x")

VOWEL_MAP = {
    "á": "a2", "à": "a3",
    "é": "e2", "è": "e3",
    "í": "i2", "ì": "i3",
    "ú": "u2", "ù": "u3"
}

LETTER_MAP = {
    "Ḫ": "H", "ḫ": "h",
    "š": "sz", "Š": "SZ",
    "ṣ": "s", "Ṣ": "S",
    "ṭ": "t", "Ṭ": "T",
}

def clean_text(text):
    if pd.isna(text):
        return ""

    text = str(text)

    # Subscripts → normal
    text = text.translate(subscript_map)

        # vowels
    for k,v in VOWEL_MAP.items():
        text = text.replace(k,v)

    # consonants
    for k,v in LETTER_MAP.items():
        text = text.replace(k,v)

    # Remove line numbers like 1' 10''
    text = re.sub(r"\b\d+('{1,2})\b", "", text)


    # gaps
    text = re.sub(r"\[\s*\.{3}\s*\]", " <big_gap> ", text)
    text = re.sub(r"\[\s*x\s*\]", " <gap> ", text)
    text = text.replace("…", " <big_gap> ")

    # # protect gap tokens
    # text = text.replace("<gap>", " GAPTOKEN ")
    # text = text.replace("<big_gap>", " BIGGAPTOKEN ")

    # remove certainty + dividers
    text = re.sub(r"[!?/:]"," ",text)

    # remove half brackets
    text = text.replace("˹","").replace("˺","")

    # remove parentheses
    text = re.sub(r"\((.*?)\)","",text)

    # remove << >> and < >
    text = re.sub(r"<<(.*?)>>", r"\1", text)
    text = re.sub(r"<(?!big_gap|gap)(.*?)>", r"\1", text)

    # # restore gap tokens
    # text = text.replace("GAPTOKEN", "<gap>")
    # text = text.replace("BIGGAPTOKEN", "<big_gap>")

    # remove [] but keep inside
    text = re.sub(r"\[(.*?)\]",r"\1",text)

    # collapse spaces
    text = re.sub(r"\s+"," ",text).strip()

    return text

In [152]:
train_df["clean_transliteration"] = train_df["transliteration"].apply(clean_text)

In [156]:
train_df.sample(5)

,oare_id,transliteration,translation,clean_transliteration
1328,d6ace566-53f6-46a8-a94d-845856ce5a9a,41 ma-na 11.5 GÍN KÙ.BABBAR ṣa-ru-pá-am ku-nu-...,"41 minas 11.5 shekels of refined silver, seale...",41 ma-na 11.5 GÍN KÙ.BABBAR sa-ru-pa2-am ku-nu...
702,6ec5d894-6733-4b4a-a99d-a32449ee1429,lá-qé-ep DUMU šu-a-šùr a-dí-in a-ša-me-ma ma-á...,... I gave to Lā-qēp son of Šu-Aššur. I hear t...,la2-qe2-ep DUMU szu-a-szu3r a-di2-in a-sza-me-...
707,6fcd5786-adcb-4503-9e00-7bcbf97a2414,i-na 16.83333 ma-na ḫu-sà-ri-im ša ik-ri-bi ša...,Of the 16 ⅚ minas of lapis lazuli from the vot...,i-na 16.83333 ma-na hu-sa3-ri-im sza ik-ri-bi ...
1130,b4fd7abc-12d2-4fde-8f30-c9310838216d,(large break) a-dí ša ta-áš-pu-ra-ni um-ma a-t...,"... Concerning what you wrote me, saying: 180 ...",a-di2 sza ta-a2sz-pu-ra-ni um-ma a-ta-ma 1 me-...
575,58bc835e-7132-47c4-9e23-ebd468c0ac6f,um-ma PUZUR₄-a-na ù a-šur-ra-bi-ma a-na šu-be-...,"Thus Puzur-Anna and Aššur-rabi, say to Šu-Bēlu...",um-ma PUZUR4-a-na u3 a-szur-ra-bi-ma a-na szu-...